# Generated by Django 6.0 on 2025-12-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_consulta',
            field=models.DateTimeField(),
        ),
    ]
