# Generated by Django 6.0 on 2025-12-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0002_alter_paciente_data_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='prioridade',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta'), ('U', 'Urgente')], default='M', max_length=1),
        ),
    ]
