# Generated by Django 6.0 on 2025-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0003_paciente_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
